const langData = {
  en: {
    home: "HOME",
    recycling: "RECYCLING",
    report: "REPORT",
    about: "ABOUT",
    myReports: "MY REPORTS",
    login: "LOGIN",
    signup: "SIGNUP",
    logout: "LOGOUT",
    welcome: "Welcome",
    heroTitle: "Cleanliness is not a duty imposed by law, but a responsibility owed to society.",
    heroSubtitle: "Every small action today creates a cleaner tomorrow.",
    recycleBtn: "Recycling Ideas",
    reportBtn: "Report",
    reportTitle: "Report Waste Issue",
    binId: "Dustbin ID",
    issueType: "Issue Type",
    selectIssue: "Select Issue Type",
    selectIssueDesc: "Please choose the problem type.",
    illegal: "Illegal Dumping",
    overflow: "Overflowing Bin",
    damaged: "Damaged Bin",
    location: "GPS Location",
    phone: "Contact Number",
    phonePlaceholder: "Enter phone number",
    descPlaceholder: "Describe the issue...",
    upload: "Upload Photo",
    submit: "Submit Report",
    submitting: "Submitting...",
    success: "Report Submitted",
    successDesc: "Thank you for helping keep the city clean!",
    fail: "Submission Failed",
    error: "Something went wrong",
    serverError: "Server Error",
    serverErrorDesc: "Unable to submit report",
    myDashboard: "My Dashboard",
    coins: "Coins Earned",
    submitted: "Reports Submitted",
    completed: "Reports Completed",
    rewards: "Redeem Rewards",
    redeem: "Redeem & Download Certificate",
    loginFirst: "Please login first",
    notEnoughCoins: "Not enough coins",
    redeemed: "Reward Redeemed",
    recycleDesc: "Learn how to manage waste efficiently and contribute to a cleaner environment.",
    solidWaste: "Solid Waste",
    organicWaste: "Organic Waste",
    hazardousWaste: "Hazardous Waste",
    solidDesc: "Includes plastics, paper, metals.",
    organicDesc: "Food waste that can be composted.",
    hazardousDesc: "Dangerous waste like batteries & chemicals.",
    tip1: "Reduce plastic usage",
    tip2: "Compost kitchen waste",
    tip3: "Recycle e-waste safely",
    recycleQuote: "Clean surroundings protect our future.",
    aboutTitle: "ABOUT US",
    aboutDesc: "GO.CLEAN is a smart waste management platform that helps citizens report waste issues easily.",
    whatWeDo: "What we do",
    whatDesc: "Users can report issues like illegal dumping, overflowing bins with images and location.",
    howWeWork: "How we work",
    howDesc: "Reports are sent to admins who manage and resolve the issues.",
    progressStatus: "Progress Status",
    progressDesc: "Track reports as Pending, In Progress, or Completed.",
    feature1: "Location-based reporting",
    feature2: "Image upload proof",
    feature3: "Live status tracking",
    aboutQuote: "Together, small actions create a big environmental impact.",
    home: "HOME",
    report: "REPORT",
    treeCert: "Tree Plantation Certificate",
    cleanBadge: "Clean Citizen Badge",
    smartAward: "Smart Citizen Award",
    feed: "FEED",
    upcomingEvents: "Upcoming Municipal Events",
eventsSubtitle: "Municipal & Community Programs",
loadingEvents: "Loading events...",
eventsError: "Could not load municipal events",
tryAgainLater: "Please check back later",
noEvents: "No upcoming events found",
  },

  hi: {
    home: "होम",
    recycling: "रीसाइक्लिंग",
    report: "रिपोर्ट",
    about: "अबाउट",
    myReports: "मेरी रिपोर्ट्स",
    login: "लॉगिन",
    signup: "साइन अप",
    logout: "लॉगआउट",
    welcome: "स्वागत",
    feed: "फीड",

    heroTitle:
      "स्वच्छता कोई कानून द्वारा थोपी गई जिम्मेदारी नहीं है, बल्कि समाज के प्रति हमारी जिम्मेदारी है।",
    heroSubtitle:
      "आज की छोटी कार्रवाई कल को साफ बनाती है।",
    recycleBtn: "रीसाइक्लिंग आइडियाज",
    reportBtn: "रिपोर्ट करें",
    reportTitle: "कचरा समस्या रिपोर्ट करें",
binId: "डस्टबिन आईडी",
issueType: "समस्या प्रकार",
selectIssue: "समस्या चुनें",
selectIssueDesc: "कृपया समस्या प्रकार चुनें",
illegal: "अवैध कचरा फेंकना",
overflow: "भरा हुआ डस्टबिन",
damaged: "टूटा हुआ डस्टबिन",
location: "जीपीएस लोकेशन",
phone: "संपर्क नंबर",
phonePlaceholder: "फोन नंबर दर्ज करें",
descPlaceholder: "समस्या का विवरण दें...",
upload: "फोटो अपलोड करें",
submit: "रिपोर्ट सबमिट करें",
submitting: "सबमिट हो रहा है...",
success: "रिपोर्ट सफलतापूर्वक भेजी गई",
successDesc: "शहर को साफ रखने में मदद के लिए धन्यवाद!",
fail: "सबमिशन असफल",
error: "कुछ गलत हुआ",
serverError: "सर्वर त्रुटि",
serverErrorDesc: "रिपोर्ट भेजने में असमर्थ",
myDashboard: "मेरा डैशबोर्ड",
coins: "कमाए गए कॉइन्स",
submitted: "सबमिट की गई रिपोर्ट्स",
completed: "पूर्ण हुई रिपोर्ट्स",
rewards: "रिवॉर्ड रिडीम करें",
redeem: "रिडीम करें और सर्टिफिकेट डाउनलोड करें",
loginFirst: "कृपया पहले लॉगिन करें",
notEnoughCoins: "पर्याप्त कॉइन्स नहीं हैं",
redeemed: "रिवॉर्ड सफलतापूर्वक रिडीम किया गया",
recycleDesc: "कचरे को सही तरीके से प्रबंधित करना सीखें और स्वच्छ पर्यावरण में योगदान दें।",
solidWaste: "ठोस कचरा",
organicWaste: "जैविक कचरा",
hazardousWaste: "खतरनाक कचरा",

solidDesc: "प्लास्टिक, कागज और धातु शामिल हैं।",
organicDesc: "खाद्य कचरा जिसे खाद बनाया जा सकता है।",
hazardousDesc: "बैटरी और रसायनों जैसा खतरनाक कचरा।",

tip1: "प्लास्टिक का उपयोग कम करें",
tip2: "रसोई के कचरे को खाद बनाएं",
tip3: "ई-वेस्ट को सुरक्षित रूप से रीसायकल करें",

recycleQuote: "स्वच्छ वातावरण हमारे भविष्य की रक्षा करता है।",
aboutTitle: "हमारे बारे में",
aboutDesc: "GO.CLEAN एक स्मार्ट वेस्ट मैनेजमेंट प्लेटफॉर्म है जो नागरिकों को कचरे की समस्या रिपोर्ट करने में मदद करता है।",

whatWeDo: "हम क्या करते हैं",
whatDesc: "उपयोगकर्ता अवैध कचरा, ओवरफ्लो बिन आदि की रिपोर्ट फोटो और लोकेशन के साथ कर सकते हैं।",

howWeWork: "हम कैसे काम करते हैं",
howDesc: "रिपोर्ट्स एडमिन को भेजी जाती हैं जो समस्या को हल करते हैं।",

progressStatus: "स्थिति अपडेट",
progressDesc: "रिपोर्ट की स्थिति Pending, In Progress या Completed के रूप में देखें।",

feature1: "लोकेशन आधारित रिपोर्टिंग",
feature2: "इमेज अपलोड प्रमाण",
feature3: "लाइव स्टेटस ट्रैकिंग",

aboutQuote: "छोटे कदम मिलकर बड़ा बदलाव लाते हैं।",
home: "होम",
report: "रिपोर्ट",

treeCert: "वृक्षारोपण प्रमाणपत्र",
cleanBadge: "स्वच्छ नागरिक बैज",
smartAward: "स्मार्ट नागरिक पुरस्कार",
upcomingEvents: "आगामी नगर कार्यक्रम",
eventsSubtitle: "नगर एवं सामुदायिक कार्यक्रम",
loadingEvents: "कार्यक्रम लोड हो रहे हैं...",
eventsError: "कार्यक्रम लोड नहीं हो सके",
tryAgainLater: "कृपया बाद में पुनः प्रयास करें",
noEvents: "कोई कार्यक्रम उपलब्ध नहीं",
  },

  bn: {
    home: "হোম",
    recycling: "রিসাইক্লিং",
    report: "রিপোর্ট",
    about: "সম্পর্কে",
    myReports: "আমার রিপোর্ট",
    login: "লগইন",
    signup: "সাইন আপ",
    logout: "লগআউট",
    welcome: "স্বাগতম",
    feed: "ফিড",

    heroTitle:
      "পরিষ্কার-পরিচ্ছন্নতা কোনো আইন দ্বারা চাপিয়ে দেওয়া দায়িত্ব নয়, বরং সমাজের প্রতি আমাদের দায়িত্ব।",
    heroSubtitle:
      "আজকের ছোট কাজ আগামীকালকে পরিষ্কার করে।",
    recycleBtn: "রিসাইক্লিং আইডিয়া",
    reportBtn: "রিপোর্ট",
    reportTitle: "বর্জ্য সমস্যা রিপোর্ট করুন",
binId: "ডাস্টবিন আইডি",
issueType: "সমস্যার ধরন",
selectIssue: "সমস্যা নির্বাচন করুন",
selectIssueDesc: "দয়া করে সমস্যার ধরন নির্বাচন করুন",
illegal: "অবৈধ আবর্জনা ফেলা",
overflow: "ভর্তি ডাস্টবিন",
damaged: "নষ্ট ডাস্টবিন",
location: "জিপিএস লোকেশন",
phone: "যোগাযোগ নম্বর",
phonePlaceholder: "ফোন নম্বর লিখুন",
descPlaceholder: "সমস্যার বর্ণনা দিন...",
upload: "ছবি আপলোড করুন",
submit: "রিপোর্ট জমা দিন",
submitting: "জমা হচ্ছে...",
success: "রিপোর্ট সফলভাবে জমা হয়েছে",
successDesc: "শহর পরিষ্কার রাখতে সাহায্যের জন্য ধন্যবাদ!",
fail: "জমা ব্যর্থ",
error: "কিছু ভুল হয়েছে",
serverError: "সার্ভার ত্রুটি",
serverErrorDesc: "রিপোর্ট পাঠানো যায়নি",
myDashboard: "আমার ড্যাশবোর্ড",
coins: "অর্জিত কয়েন",
submitted: "জমা দেওয়া রিপোর্ট",
completed: "সম্পন্ন রিপোর্ট",
rewards: "রিওয়ার্ড গ্রহণ করুন",
redeem: "রিডিম করে সার্টিফিকেট ডাউনলোড করুন",
loginFirst: "দয়া করে আগে লগইন করুন",
notEnoughCoins: "পর্যাপ্ত কয়েন নেই",
redeemed: "রিওয়ার্ড সফলভাবে গ্রহণ করা হয়েছে",
recycleDesc: "বর্জ্য সঠিকভাবে পরিচালনা করতে শিখুন এবং পরিষ্কার পরিবেশে অবদান রাখুন।",
solidWaste: "কঠিন বর্জ্য",
organicWaste: "জৈব বর্জ্য",
hazardousWaste: "বিপজ্জনক বর্জ্য",

solidDesc: "প্লাস্টিক, কাগজ এবং ধাতু অন্তর্ভুক্ত।",
organicDesc: "খাদ্য বর্জ্য যা কম্পোস্ট করা যায়।",
hazardousDesc: "ব্যাটারি এবং রাসায়নিকের মতো বিপজ্জনক বর্জ্য।",

tip1: "প্লাস্টিক ব্যবহার কমান",
tip2: "রান্নাঘরের বর্জ্য কম্পোস্ট করুন",
tip3: "ই-ওয়েস্ট নিরাপদে রিসাইকেল করুন",

recycleQuote: "পরিষ্কার পরিবেশ আমাদের ভবিষ্যৎ রক্ষা করে।",
aboutTitle: "আমাদের সম্পর্কে",
aboutDesc: "GO.CLEAN একটি স্মার্ট বর্জ্য ব্যবস্থাপনা প্ল্যাটফর্ম যা নাগরিকদের সমস্যার রিপোর্ট করতে সাহায্য করে।",

whatWeDo: "আমরা কি করি",
whatDesc: "ব্যবহারকারীরা ছবি ও লোকেশন সহ বর্জ্যের সমস্যা রিপোর্ট করতে পারে।",

howWeWork: "আমরা কিভাবে কাজ করি",
howDesc: "রিপোর্টগুলি অ্যাডমিনদের কাছে পাঠানো হয় যারা সমস্যার সমাধান করে।",

progressStatus: "অবস্থা আপডেট",
progressDesc: "Pending, In Progress বা Completed হিসাবে রিপোর্টের অবস্থা দেখুন।",

feature1: "লোকেশন ভিত্তিক রিপোর্টিং",
feature2: "ছবি আপলোড প্রমাণ",
feature3: "লাইভ স্ট্যাটাস ট্র্যাকিং",

aboutQuote: "ছোট ছোট কাজ মিলেই বড় পরিবর্তন আনে।",
home: "হোম",
report: "রিপোর্ট",

treeCert: "গাছ রোপণ সার্টিফিকেট",
cleanBadge: "পরিচ্ছন্ন নাগরিক ব্যাজ",
smartAward: "স্মার্ট নাগরিক পুরস্কার",
upcomingEvents: "আসন্ন পৌরসভা ইভেন্ট",
eventsSubtitle: "পৌর ও কমিউনিটি প্রোগ্রাম",
loadingEvents: "ইভেন্ট লোড হচ্ছে...",
eventsError: "ইভেন্ট লোড করা যায়নি",
tryAgainLater: "অনুগ্রহ করে পরে আবার চেষ্টা করুন",
noEvents: "কোন ইভেন্ট পাওয়া যায়নি",
  },

  ta: {
    home: "முகப்பு",
    recycling: "மறுசுழற்சி",
    report: "அறிக்கை",
    about: "பற்றி",
    myReports: "என் அறிக்கைகள்",
    login: "உள்நுழை",
    signup: "பதிவு",
    logout: "வெளியேறு",
    welcome: "வரவேற்கிறோம்",
    feed: "பதிவு",

    heroTitle:
      "சுத்தம் என்பது சட்டம் விதித்த கடமை அல்ல, சமூகத்திற்கு நாம் கடமைப்பட்ட பொறுப்பு.",
    heroSubtitle:
      "இன்றைய சிறிய செயல் நாளைய சுத்தமான உலகை உருவாக்கும்.",
    recycleBtn: "மறுசுழற்சி யோசனைகள்",
    reportBtn: "அறிக்கை",
    reportTitle: "கழிவு பிரச்சினையை புகாரளிக்கவும்",
binId: "டஸ்ட்பின் ஐடி",
issueType: "பிரச்சனை வகை",
selectIssue: "பிரச்சனை தேர்ந்தெடுக்கவும்",
selectIssueDesc: "பிரச்சனை வகையை தேர்வு செய்யவும்",
illegal: "அனுமதியற்ற குப்பை கொட்டுதல்",
overflow: "நிரம்பிய டஸ்ட்பின்",
damaged: "சேதமடைந்த டஸ்ட்பின்",
location: "ஜிபிஎஸ் இடம்",
phone: "தொடர்பு எண்",
phonePlaceholder: "தொலைபேசி எண்ணை உள்ளிடவும்",
descPlaceholder: "பிரச்சனையை விவரிக்கவும்...",
upload: "புகைப்படத்தை பதிவேற்றவும்",
submit: "புகாரை சமர்ப்பிக்கவும்",
submitting: "சமர்ப்பிக்கப்படுகிறது...",
success: "புகார் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது",
successDesc: "நகரத்தை சுத்தமாக வைத்திருக்க உதவியதற்கு நன்றி!",
fail: "சமர்ப்பிப்பு தோல்வி",
error: "ஏதோ தவறு நடந்தது",
serverError: "சர்வர் பிழை",
serverErrorDesc: "புகாரை அனுப்ப முடியவில்லை",
myDashboard: "என் டாஷ்போர்டு",
coins: "சம்பாதித்த நாணயங்கள்",
submitted: "சமர்ப்பிக்கப்பட்ட அறிக்கைகள்",
completed: "முடிக்கப்பட்ட அறிக்கைகள்",
rewards: "விருதுகளை பெறுங்கள்",
redeem: "பரிசை பெறவும் மற்றும் சான்றிதழை பதிவிறக்கவும்",
loginFirst: "முதலில் உள்நுழையவும்",
notEnoughCoins: "போதுமான நாணயங்கள் இல்லை",
redeemed: "விருது வெற்றிகரமாக பெறப்பட்டது",
recycleDesc: "கழிவுகளை சரியாக நிர்வகிக்க கற்றுக்கொள்ளுங்கள் மற்றும் சுத்தமான சூழலை உருவாக்க உதவுங்கள்.",
solidWaste: "திடக் கழிவு",
organicWaste: "உயிரியல் கழிவு",
hazardousWaste: "ஆபத்தான கழிவு",

solidDesc: "பிளாஸ்டிக், காகிதம், உலோகம் அடங்கும்.",
organicDesc: "உணவு கழிவுகளை உரமாக மாற்றலாம்.",
hazardousDesc: "பேட்டரி மற்றும் ரசாயனங்கள் போன்ற ஆபத்தான கழிவுகள்.",

tip1: "பிளாஸ்டிக் பயன்பாட்டை குறைக்கவும்",
tip2: "சமையலறை கழிவுகளை உரமாக மாற்றவும்",
tip3: "இ-வேஸ்டை பாதுகாப்பாக மறுசுழற்சி செய்யவும்",

recycleQuote: "சுத்தமான சூழல் நம் எதிர்காலத்தை பாதுகாக்கும்.",
aboutTitle: "எங்களை பற்றி",
aboutDesc: "GO.CLEAN ஒரு ஸ்மார்ட் கழிவு மேலாண்மை தளம் ஆகும்.",

whatWeDo: "நாம் என்ன செய்கிறோம்",
whatDesc: "பயனர்கள் புகைப்படம் மற்றும் இடத்துடன் கழிவு பிரச்சினைகளை புகாரளிக்கலாம்.",

howWeWork: "நாம் எப்படி செயல்படுகிறோம்",
howDesc: "புகார்கள் நிர்வாகிகளுக்கு அனுப்பப்பட்டு தீர்வு காணப்படும்.",

progressStatus: "நிலை மேம்பாடு",
progressDesc: "Pending, In Progress அல்லது Completed என நிலையை பார்க்கலாம்.",

feature1: "இட அடிப்படையிலான புகார்",
feature2: "புகைப்பட ஆதாரம்",
feature3: "நேரடி நிலை கண்காணிப்பு",

aboutQuote: "சிறிய செயல்கள் பெரிய மாற்றத்தை உருவாக்கும்.",
home: "முகப்பு",
report: "அறிக்கை",

treeCert: "மர நடவு சான்றிதழ்",
cleanBadge: "சுத்தமான குடிமகன் பதக்கம்",
smartAward: "சிறந்த குடிமகன் விருது",
upcomingEvents: "வரவிருக்கும் மாநகர நிகழ்வுகள்",
eventsSubtitle: "மாநகர மற்றும் சமூக நிகழ்ச்சிகள்",
loadingEvents: "நிகழ்வுகள் ஏற்றப்படுகிறது...",
eventsError: "நிகழ்வுகளை ஏற்ற முடியவில்லை",
tryAgainLater: "பின்னர் மீண்டும் முயற்சிக்கவும்",
noEvents: "எந்த நிகழ்வும் கிடைக்கவில்லை",
  },

  te: {
    home: "హోమ్",
    recycling: "రీసైక్లింగ్",
    report: "రిపోర్ట్",
    about: "గురించి",
    myReports: "నా రిపోర్ట్స్",
    login: "లాగిన్",
    signup: "సైన్ అప్",
    logout: "లాగౌట్",
    welcome: "స్వాగతం",
    feed: "ఫీడ్",

    heroTitle:
      "శుభ్రత అనేది చట్టం విధించిన బాధ్యత కాదు, సమాజానికి మన బాధ్యత.",
    heroSubtitle:
      "ఈ రోజు చిన్న చర్య రేపు శుభ్రమైన ప్రపంచాన్ని సృష్టిస్తుంది.",
    recycleBtn: "రీసైక్లింగ్ ఐడియాస్",
    reportBtn: "రిపోర్ట్",
    reportTitle: "వ్యర్థ సమస్యను నివేదించండి",
binId: "డస్ట్‌బిన్ ఐడి",
issueType: "సమస్య రకం",
selectIssue: "సమస్యను ఎంచుకోండి",
selectIssueDesc: "దయచేసి సమస్య రకం ఎంచుకోండి",
illegal: "అక్రమంగా చెత్త వేయడం",
overflow: "పూర్తిగా నిండిన బిన్",
damaged: "పాడైన బిన్",
location: "జీపీఎస్ స్థానం",
phone: "ఫోన్ నంబర్",
phonePlaceholder: "ఫోన్ నంబర్ నమోదు చేయండి",
descPlaceholder: "సమస్య వివరించండి...",
upload: "ఫోటో అప్‌లోడ్ చేయండి",
submit: "నివేదిక పంపండి",
submitting: "పంపుతోంది...",
success: "నివేదిక విజయవంతంగా పంపబడింది",
successDesc: "నగరాన్ని శుభ్రంగా ఉంచడంలో సహాయం చేసినందుకు ధన్యవాదాలు!",
fail: "పంపడం విఫలమైంది",
error: "ఏదో తప్పు జరిగింది",
serverError: "సర్వర్ లోపం",
serverErrorDesc: "నివేదిక పంపలేకపోయాం",
myDashboard: "నా డాష్‌బోర్డ్",
coins: "సంపాదించిన నాణేలు",
submitted: "సమర్పించిన నివేదికలు",
completed: "పూర్తయిన నివేదికలు",
rewards: "బహుమతులు పొందండి",
redeem: "రిడీమ్ చేసి సర్టిఫికేట్ డౌన్‌లోడ్ చేయండి",
loginFirst: "దయచేసి ముందుగా లాగిన్ అవ్వండి",
notEnoughCoins: "తగినన్ని నాణేలు లేవు",
redeemed: "బహుమతి విజయవంతంగా పొందబడింది",
recycleDesc: "వ్యర్థాలను సరిగ్గా నిర్వహించడం నేర్చుకోండి మరియు శుభ్రమైన పర్యావరణానికి సహాయం చేయండి.",
solidWaste: "ఘన వ్యర్థాలు",
organicWaste: "సేంద్రీయ వ్యర్థాలు",
hazardousWaste: "ప్రమాదకర వ్యర్థాలు",

solidDesc: "ప్లాస్టిక్, కాగితం, లోహాలు ఉన్నాయి.",
organicDesc: "ఆహార వ్యర్థాలను కంపోస్ట్ చేయవచ్చు.",
hazardousDesc: "బ్యాటరీలు మరియు రసాయనాలు వంటి ప్రమాదకర వ్యర్థాలు.",

tip1: "ప్లాస్టిక్ వినియోగాన్ని తగ్గించండి",
tip2: "వంటగది వ్యర్థాలను కంపోస్ట్ చేయండి",
tip3: "ఈ-వేస్ట్‌ను సురక్షితంగా రీసైకిల్ చేయండి",

recycleQuote: "శుభ్రమైన పర్యావరణం మన భవిష్యత్తును రక్షిస్తుంది.",
aboutTitle: "మా గురించి",
aboutDesc: "GO.CLEAN ఒక స్మార్ట్ వ్యర్థ నిర్వహణ వేదిక.",

whatWeDo: "మేము ఏమి చేస్తాము",
whatDesc: "వినియోగదారులు ఫోటో మరియు స్థానం తో సమస్యలను నివేదించవచ్చు.",

howWeWork: "మేము ఎలా పనిచేస్తాము",
howDesc: "నివేదికలు అడ్మిన్‌కి పంపబడతాయి మరియు పరిష్కరించబడతాయి.",

progressStatus: "స్థితి అప్డేట్",
progressDesc: "Pending, In Progress లేదా Completed గా స్థితిని చూడండి.",

feature1: "స్థానం ఆధారిత నివేదిక",
feature2: "చిత్ర ఆధారం",
feature3: "లైవ్ ట్రాకింగ్",

aboutQuote: "చిన్న చర్యలు పెద్ద మార్పును తెస్తాయి.",
home: "హోమ్",
report: "రిపోర్ట్",

treeCert: "చెట్టు నాటకం సర్టిఫికేట్",
cleanBadge: "శుభ్రమైన పౌర బ్యాడ్జ్",
smartAward: "స్మార్ట్ పౌర అవార్డు",
upcomingEvents: "వచ్చే మునిసిపల్ ఈవెంట్స్",
eventsSubtitle: "మునిసిపల్ & కమ్యూనిటీ ప్రోగ్రామ్స్",
loadingEvents: "ఈవెంట్స్ లోడ్ అవుతోంది...",
eventsError: "మునిసిపల్ ఈవెంట్స్ లోడ్ చేయలేకపోయాం",
tryAgainLater: "దయచేసి తర్వాత ప్రయత్నించండి",
noEvents: "ఏమి ఈవెంట్స్ కనుగొనబడలేదు",


  },

  mr: {
    home: "होम",
    recycling: "रीसायकलिंग",
    report: "रिपोर्ट",
    about: "बद्दल",
    myReports: "माझे रिपोर्ट्स",
    login: "लॉगिन",
    signup: "साइनअप",
    logout: "लॉगआउट",
    welcome: "स्वागत",
    feed: "फीड",

    heroTitle:
      "स्वच्छता ही कायद्याने लादलेली जबाबदारी नसून समाजाप्रती आपली जबाबदारी आहे.",
    heroSubtitle:
      "आजची छोटी कृती उद्याचा स्वच्छ जग निर्माण करते.",
    recycleBtn: "रीसायकलिंग कल्पना",
    reportBtn: "रिपोर्ट",
    reportTitle: "कचरा समस्या नोंदवा",
binId: "डस्टबिन आयडी",
issueType: "समस्या प्रकार",
selectIssue: "समस्या निवडा",
selectIssueDesc: "कृपया समस्या प्रकार निवडा",
illegal: "बेकायदेशीर कचरा टाकणे",
overflow: "भरलेला डस्टबिन",
damaged: "तुटलेला डस्टबिन",
location: "जीपीएस स्थान",
phone: "संपर्क क्रमांक",
phonePlaceholder: "फोन नंबर टाका",
descPlaceholder: "समस्येचे वर्णन करा...",
upload: "फोटो अपलोड करा",
submit: "रिपोर्ट सबमिट करा",
submitting: "सबमिट होत आहे...",
success: "रिपोर्ट यशस्वीरित्या सबमिट झाला",
successDesc: "शहर स्वच्छ ठेवण्यासाठी मदत केल्याबद्दल धन्यवाद!",
fail: "सबमिशन अयशस्वी",
error: "काहीतरी चूक झाली",
serverError: "सर्व्हर त्रुटी",
serverErrorDesc: "रिपोर्ट सबमिट करता आला नाही",
reportTitle: "कचरा समस्या नोंदवा",
binId: "डस्टबिन आयडी",
issueType: "समस्या प्रकार",
selectIssue: "समस्या निवडा",
selectIssueDesc: "कृपया समस्या प्रकार निवडा",
illegal: "बेकायदेशीर कचरा टाकणे",
overflow: "भरलेला डस्टबिन",
damaged: "तुटलेला डस्टबिन",
location: "जीपीएस स्थान",
phone: "संपर्क क्रमांक",
phonePlaceholder: "फोन नंबर टाका",
descPlaceholder: "समस्येचे वर्णन करा...",
upload: "फोटो अपलोड करा",
submit: "रिपोर्ट सबमिट करा",
submitting: "सबमिट होत आहे...",
success: "रिपोर्ट यशस्वीरित्या सबमिट झाला",
successDesc: "शहर स्वच्छ ठेवण्यासाठी मदत केल्याबद्दल धन्यवाद!",
fail: "सबमिशन अयशस्वी",
error: "काहीतरी चूक झाली",
serverError: "सर्व्हर त्रुटी",
serverErrorDesc: "रिपोर्ट सबमिट करता आला नाही",
myDashboard: "माझा डॅशबोर्ड",
coins: "मिळालेले कॉइन्स",
submitted: "सबमिट केलेल्या रिपोर्ट्स",
completed: "पूर्ण झालेल्या रिपोर्ट्स",
rewards: "रिवॉर्ड मिळवा",
redeem: "रिडीम करा आणि सर्टिफिकेट डाउनलोड करा",
loginFirst: "कृपया आधी लॉगिन करा",
notEnoughCoins: "पुरेसे कॉइन्स नाहीत",
redeemed: "रिवॉर्ड यशस्वीरित्या मिळाला",
recycleDesc: "कचरा योग्य प्रकारे व्यवस्थापित करायला शिका आणि स्वच्छ पर्यावरणासाठी योगदान द्या.",
solidWaste: "घन कचरा",
organicWaste: "सेंद्रिय कचरा",
hazardousWaste: "धोकादायक कचरा",

solidDesc: "प्लास्टिक, कागद आणि धातू समाविष्ट आहेत.",
organicDesc: "अन्न कचरा कंपोस्ट करता येतो.",
hazardousDesc: "बॅटरी आणि रसायनांसारखा धोकादायक कचरा.",

tip1: "प्लास्टिक वापर कमी करा",
tip2: "स्वयंपाकघरातील कचरा कंपोस्ट करा",
tip3: "ई-कचरा सुरक्षितपणे रीसायकल करा",

recycleQuote: "स्वच्छ वातावरण आपले भविष्य सुरक्षित ठेवते.",
aboutTitle: "आमच्याबद्दल",
aboutDesc: "GO.CLEAN हे स्मार्ट कचरा व्यवस्थापन प्लॅटफॉर्म आहे.",

whatWeDo: "आम्ही काय करतो",
whatDesc: "वापरकर्ते फोटो आणि लोकेशनसह समस्या नोंदवू शकतात.",

howWeWork: "आम्ही कसे काम करतो",
howDesc: "रिपोर्ट अॅडमिनकडे जातात आणि त्यांचे निराकरण केले जाते.",

progressStatus: "स्थिती अपडेट",
progressDesc: "Pending, In Progress किंवा Completed स्थिती पाहा.",

feature1: "लोकेशन आधारित रिपोर्टिंग",
feature2: "इमेज अपलोड",
feature3: "लाइव्ह ट्रॅकिंग",

aboutQuote: "लहान कृती मोठा बदल घडवतात.",
home: "मुख्यपृष्ठ",
report: "रिपोर्ट",

treeCert: "वृक्षारोपण प्रमाणपत्र",
cleanBadge: "स्वच्छ नागरिक बॅज",
smartAward: "स्मार्ट नागरिक पुरस्कार",
upcomingEvents: "आगामी नगरपालिका कार्यक्रम",
eventsSubtitle: "नगरपालिका और सामुदायिक कार्यक्रम",
loadingEvents: "कार्यक्रम लोड हो रहे हैं...",
eventsError: "कार्यक्रम लोड नहीं हो सके",
tryAgainLater: "कृपया बाद में पुनः प्रयास करें",
noEvents: "कोई आगामी कार्यक्रम नहीं मिला",
  },

  gu: {
    home: "હોમ",
    recycling: "રીસાયક્લિંગ",
    report: "રિપોર્ટ",
    about: "વિશે",
    myReports: "મારા રિપોર્ટ્સ",
    login: "લોગિન",
    signup: "સાઇન અપ",
    logout: "લોગઆઉટ",
    welcome: "સ્વાગત",
    feed: "ફીડ",

    heroTitle:
      "સફાઈ કોઈ કાયદા દ્વારા લાદવામાં આવેલી ફરજ નથી, પરંતુ સમાજ પ્રત્યે આપણી જવાબદારી છે.",
    heroSubtitle:
      "આજનું નાનું પગલું આવતીકાલે સ્વચ્છ દુનિયા બનાવે છે.",
    recycleBtn: "રીસાયક્લિંગ આઈડિયા",
    reportBtn: "રિપોર્ટ",
    reportTitle: "કચરો સમસ્યા રિપોર્ટ કરો",
binId: "ડસ્ટબિન આઈડી",
issueType: "સમस्या પ્રકાર",
selectIssue: "સમસા પસંદ કરો",
selectIssueDesc: "કૃપા કરીને સમસ્યા પસંદ કરો",
illegal: "ગેરકાયદેસર કચરો ફેંકવો",
overflow: "ભરાયેલ ડસ્ટબિન",
damaged: "તૂટેલું ડસ્ટબિન",
location: "GPS સ્થાન",
phone: "સંપર્ક નંબર",
phonePlaceholder: "ફોન નંબર દાખલ કરો",
descPlaceholder: "સમસ્યા વર્ણવો...",
upload: "ફોટો અપલોડ કરો",
submit: "રિપોર્ટ સબમિટ કરો",
submitting: "સબમિટ થઈ રહ્યું છે...",
success: "રિપોર્ટ સફળતાપૂર્વક સબમિટ થયો",
successDesc: "શહેર સ્વચ્છ રાખવામાં મદદ માટે આભાર!",
fail: "સબમિશન નિષ્ફળ",
error: "કઈક ખોટું થયું",
serverError: "સર્વર ભૂલ",
serverErrorDesc: "રિપોર્ટ મોકલી શકાયો નહીં",
myDashboard: "મારું ડેશબોર્ડ",
coins: "મેળવેલા કોઇન્સ",
submitted: "સબમિટ કરેલી રિપોર્ટ્સ",
completed: "પૂર્ણ થયેલી રિપોર્ટ્સ",
rewards: "રિવોર્ડ મેળવો",
redeem: "રિડીમ કરો અને સર્ટિફિકેટ ડાઉનલોડ કરો",
loginFirst: "કૃપા કરીને પહેલા લોગિન કરો",
notEnoughCoins: "પર્યાપ્ત કોઇન્સ નથી",
redeemed: "રિવોર્ડ સફળતાપૂર્વક મેળવ્યો",
recycleDesc: "કચરાનું યોગ્ય સંચાલન શીખો અને સ્વચ્છ પર્યાવરણ માટે યોગદાન આપો.",
solidWaste: "ઘન કચરો",
organicWaste: "સેન્દ્રિય કચરો",
hazardousWaste: "જોખમી કચરો",

solidDesc: "પ્લાસ્ટિક, કાગળ અને ધાતુઓનો સમાવેશ થાય છે.",
organicDesc: "ખોરાકનો કચરો કમ્પોસ્ટ કરી શકાય છે.",
hazardousDesc: "બેટરી અને રસાયણ જેવા જોખમી કચરા.",

tip1: "પ્લાસ્ટિકનો ઉપયોગ ઓછો કરો",
tip2: "રસોડાના કચરાને કમ્પોસ્ટ કરો",
tip3: "ઇ-વેસ્ટને સુરક્ષિત રીતે રિસાયકલ કરો",

recycleQuote: "સ્વચ્છ પર્યાવરણ આપણું ભવિષ્ય સુરક્ષિત રાખે છે.",
aboutTitle: "અમારા વિશે",
aboutDesc: "GO.CLEAN એક સ્માર્ટ કચરો મેનેજમેન્ટ પ્લેટફોર્મ છે.",

whatWeDo: "અમે શું કરીએ",
whatDesc: "વપરાશકર્તાઓ ફોટો અને લોકેશન સાથે સમસ્યા રિપોર્ટ કરી શકે છે.",

howWeWork: "અમે કેવી રીતે કામ કરીએ",
howDesc: "રિપોર્ટ એડમિન સુધી પહોંચે છે અને ઉકેલાય છે.",

progressStatus: "સ્થિતિ અપડેટ",
progressDesc: "Pending, In Progress અથવા Completed સ્થિતિ જુઓ.",

feature1: "લોકેશન આધારિત રિપોર્ટિંગ",
feature2: "ઇમેજ પ્રૂફ",
feature3: "લાઈવ ટ્રેકિંગ",

aboutQuote: "નાની ક્રિયાઓ મોટો ફેરફાર લાવે છે.",
home: "હોમ",
report: "રિપોર્ટ",

treeCert: "વૃક્ષારોપણ પ્રમાણપત્ર",
cleanBadge: "સ્વચ્છ નાગરિક બેજ",
smartAward: "સ્માર્ટ નાગરિક એવોર્ડ",
upcomingEvents: "આગામી મ્યુનિસિપલ ઇવેન્ટ્સ",
eventsSubtitle: "મ્યુનિસિપલ અને સમુદાય કાર્યક્રમો",
loadingEvents: "ઇવેન્ટ્સ લોડ થઈ રહ્યા છે...",
eventsError: "ઇવેન્ટ્સ લોડ કરી શક્યા નથી",
tryAgainLater: "કૃપા કરીને પછી ફરી પ્રયાસ કરો",
noEvents: "કોઈ ઇવેન્ટ્સ મળ્યા નથી",
  },

  kn: {
    home: "ಹೋಮ್",
    recycling: "ರಿಸೈಕ್ಲಿಂಗ್",
    report: "ವರದಿ",
    about: "ಬಗ್ಗೆ",
    myReports: "ನನ್ನ ವರದಿಗಳು",
    login: "ಲಾಗಿನ್",
    signup: "ಸೈನ್ ಅಪ್",
    logout: "ಲಾಗೌಟ್",
    welcome: "ಸ್ವಾಗತ",
    feed: "ಫೀಡ್",

    heroTitle:
      "ಸ್ವಚ್ಛತೆ ಕಾನೂನು ಹೇರಿದ ಕರ್ತವ್ಯವಲ್ಲ, ಸಮಾಜದ ಪ್ರತಿಯೊಬ್ಬರ ಜವಾಬ್ದಾರಿ.",
    heroSubtitle:
      "ಇಂದು ಮಾಡಿದ ಸಣ್ಣ ಕೆಲಸ ನಾಳೆ ಸ್ವಚ್ಛ ಲೋಕವನ್ನು ನಿರ್ಮಿಸುತ್ತದೆ.",

    recycleBtn: "ರಿಸೈಕ್ಲಿಂಗ್ ಐಡಿಯಾಸ್",
    reportBtn: "ವರದಿ",

    reportTitle: "ತ್ಯಾಜ್ಯ ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಿ",
    binId: "ಡಸ್ಟ್‌ಬಿನ್ ಐಡಿ",
    issueType: "ಸಮಸ್ಯೆಯ ಪ್ರಕಾರ",
    selectIssue: "ಸಮಸ್ಯೆ ಆಯ್ಕೆಮಾಡಿ",
    selectIssueDesc: "ದಯವಿಟ್ಟು ಸಮಸ್ಯೆಯ ಪ್ರಕಾರ ಆಯ್ಕೆಮಾಡಿ",

    illegal: "ಅಕ್ರಮವಾಗಿ ಕಸ ತ್ಯಜಿಸುವುದು",
    overflow: "ಪೂರ್ಣವಾದ ಡಸ್ಟ್‌ಬಿನ್",
    damaged: "ಹಾನಿಗೊಂಡ ಡಸ್ಟ್‌ಬಿನ್",

    location: "GPS ಸ್ಥಳ",
    phone: "ಸಂಪರ್ಕ ಸಂಖ್ಯೆ",
    phonePlaceholder: "ಫೋನ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
    descPlaceholder: "ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಿ...",

    upload: "ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    submit: "ವರದಿ ಸಲ್ಲಿಸಿ",
    submitting: "ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...",
    success: "ವರದಿ ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ",
    successDesc: "ನಗರವನ್ನು ಸ್ವಚ್ಛವಾಗಿಡಲು ಸಹಾಯ ಮಾಡಿದಕ್ಕಾಗಿ ಧನ್ಯವಾದಗಳು!",

    fail: "ಸಲ್ಲಿಕೆ ವಿಫಲವಾಗಿದೆ",
    error: "ಏನೋ ತಪ್ಪಾಗಿದೆ",
    serverError: "ಸರ್ವರ್ ದೋಷ",
    serverErrorDesc: "ವರದಿ ಸಲ್ಲಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ",

    myDashboard: "ನನ್ನ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    coins: "ಪಡೆಯಲಾದ ನಾಣ್ಯಗಳು",
    submitted: "ಸಲ್ಲಿಸಿದ ವರದಿಗಳು",
    completed: "ಪೂರ್ಣಗೊಂಡ ವರದಿಗಳು",
    rewards: "ಬಹುಮಾನಗಳನ್ನು ಪಡೆಯಿರಿ",
    redeem: "ರೀಡೀಮ್ ಮಾಡಿ ಪ್ರಮಾಣಪತ್ರ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
    loginFirst: "ದಯವಿಟ್ಟು ಮೊದಲು ಲಾಗಿನ್ ಮಾಡಿ",
    notEnoughCoins: "ಸಾಕಷ್ಟು ನಾಣ್ಯಗಳಿಲ್ಲ",
    redeemed: "ಬಹುಮಾನ ಯಶಸ್ವಿಯಾಗಿ ಪಡೆದಿದೆ",
    recycleDesc: "ತ್ಯಾಜ್ಯವನ್ನು ಸರಿಯಾಗಿ ನಿರ್ವಹಿಸುವುದನ್ನು ಕಲಿಯಿರಿ ಮತ್ತು ಸ್ವಚ್ಛ ಪರಿಸರಕ್ಕೆ ಸಹಾಯಮಾಡಿ.",
solidWaste: "ಘನ ತ್ಯಾಜ್ಯ",
organicWaste: "ಸೇಂದ್ರೀಯ ತ್ಯಾಜ್ಯ",
hazardousWaste: "ಅಪಾಯಕಾರಿ ತ್ಯಾಜ್ಯ",

solidDesc: "ಪ್ಲಾಸ್ಟಿಕ್, ಕಾಗದ ಮತ್ತು ಲೋಹಗಳು ಸೇರಿವೆ.",
organicDesc: "ಆಹಾರ ತ್ಯಾಜ್ಯವನ್ನು ಕಂಪೋಸ್ಟ್ ಮಾಡಬಹುದು.",
hazardousDesc: "ಬ್ಯಾಟರಿ ಮತ್ತು ರಸಾಯನಗಳಂತಹ ಅಪಾಯಕಾರಿ ತ್ಯಾಜ್ಯ.",

tip1: "ಪ್ಲಾಸ್ಟಿಕ್ ಬಳಕೆಯನ್ನು ಕಡಿಮೆ ಮಾಡಿ",
tip2: "ಅಡಿಗೆಮನೆ ತ್ಯಾಜ್ಯವನ್ನು ಕಂಪೋಸ್ಟ್ ಮಾಡಿ",
tip3: "ಇ-ವೇಸ್ಟ್ ಅನ್ನು ಸುರಕ್ಷಿತವಾಗಿ ಮರುಬಳಕೆ ಮಾಡಿ",

recycleQuote: "ಸ್ವಚ್ಛ ಪರಿಸರ ನಮ್ಮ ಭವಿಷ್ಯವನ್ನು ರಕ್ಷಿಸುತ್ತದೆ.",
aboutTitle: "ನಮ್ಮ ಬಗ್ಗೆ",
aboutDesc: "GO.CLEAN ಒಂದು ಸ್ಮಾರ್ಟ್ ತ್ಯಾಜ್ಯ ನಿರ್ವಹಣಾ ವೇದಿಕೆ.",

whatWeDo: "ನಾವು ಏನು ಮಾಡುತ್ತೇವೆ",
whatDesc: "ಬಳಕೆದಾರರು ಫೋಟೋ ಮತ್ತು ಸ್ಥಳದೊಂದಿಗೆ ಸಮಸ್ಯೆಗಳನ್ನು ವರದಿ ಮಾಡಬಹುದು.",

howWeWork: "ನಾವು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತೇವೆ",
howDesc: "ರಿಪೋರ್ಟ್‌ಗಳು ಆಡ್ಮಿನ್‌ಗೆ ಹೋಗುತ್ತವೆ ಮತ್ತು ಪರಿಹರಿಸಲಾಗುತ್ತದೆ.",

progressStatus: "ಸ್ಥಿತಿ ಅಪ್ಡೇಟ್",
progressDesc: "Pending, In Progress ಅಥವಾ Completed ಸ್ಥಿತಿಯನ್ನು ನೋಡಿ.",

feature1: "ಸ್ಥಳ ಆಧಾರಿತ ವರದಿ",
feature2: "ಚಿತ್ರದ ಸಾಕ್ಷಿ",
feature3: "ಲೈವ್ ಟ್ರ್ಯಾಕಿಂಗ್",

aboutQuote: "ಸಣ್ಣ ಕ್ರಿಯೆಗಳು ದೊಡ್ಡ ಬದಲಾವಣೆ ತರಬಹುದು.",
home: "ಮುಖಪುಟ",
report: "ವರದಿ",

treeCert: "ಮರ ನೆಡುವ ಪ್ರಮಾಣಪತ್ರ",
cleanBadge: "ಸ್ವಚ್ಛ ನಾಗರಿಕ ಬ್ಯಾಡ್ಜ್",
smartAward: "ಸ್ಮಾರ್ಟ್ ನಾಗರಿಕ ಪ್ರಶಸ್ತಿ",
upcomingEvents: "ಬರುವ ಮ್ಯುನಿಸಿಪಲ್ ಈವೆಂಟ್ಸ್",
eventsSubtitle: "ಮ್ಯುನಿಸಿಪಲ್ ಮತ್ತು ಸಮುದಾಯ ಕಾರ್ಯಕ್ರಮಗಳು",
loadingEvents: "ಈವೆಂಟ್ಸ್ ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
eventsError: "ಈವೆಂಟ್ಸ್ ಲೋಡ್ ಮಾಡಲಾಗಲಿಲ್ಲ",
tryAgainLater: "ದಯವಿಟ್ಟು ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
noEvents: "ಯಾವುದೇ ಈವೆಂಟ್ಸ್ ಕಂಡುಬಂದಿಲ್ಲ",
  },

  ml: {
    home: "ഹോം",
    recycling: "റിസൈക്ലിംഗ്",
    report: "റിപ്പോർട്ട്",
    about: "കുറിച്ച്",
    myReports: "എന്റെ റിപ്പോർട്ടുകൾ",
    login: "ലോഗിൻ",
    signup: "സൈൻ അപ്പ്",
    logout: "ലോഗൗട്ട്",
    welcome: "സ്വാഗതം",
    feed: "ഫീഡ്",

    heroTitle:
      "ശുചിത്വം നിയമം നിർബന്ധിതമാക്കിയ കടമയല്ല, സമൂഹത്തോടുള്ള ഉത്തരവാദിത്തമാണ്.",
    heroSubtitle:
      "ഇന്നത്തെ ചെറിയ പ്രവർത്തനം നാളെയെ ശുചിയാക്കും.",
    recycleBtn: "റിസൈക്ലിംഗ് ആശയങ്ങൾ",
    reportBtn: "റിപ്പോർട്ട്",
    reportTitle: "മാലിന്യ പ്രശ്നം റിപ്പോർട്ട് ചെയ്യുക",
binId: "ഡസ്റ്റ്‌ബിൻ ഐഡി",
issueType: "പ്രശ്നത്തിന്റെ തരം",
selectIssue: "പ്രശ്നം തിരഞ്ഞെടുക്കുക",
selectIssueDesc: "ദയവായി പ്രശ്നത്തിന്റെ തരം തിരഞ്ഞെടുക്കുക",
illegal: "നിയമവിരുദ്ധമായി മാലിന്യം ഇടൽ",
overflow: "നിറഞ്ഞ ഡസ്റ്റ്‌ബിൻ",
damaged: "നശിച്ച ഡസ്റ്റ്‌ബിൻ",
location: "GPS സ്ഥലം",
phone: "ഫോൺ നമ്പർ",
phonePlaceholder: "ഫോൺ നമ്പർ നൽകുക",
descPlaceholder: "പ്രശ്നം വിശദീകരിക്കുക...",
upload: "ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക",
submit: "റിപ്പോർട്ട് സമർപ്പിക്കുക",
submitting: "സമർപ്പിക്കുന്നു...",
success: "റിപ്പോർട്ട് വിജയകരമായി സമർപ്പിച്ചു",
successDesc: "നഗരം ശുചിയായി നിലനിർത്താൻ സഹായിച്ചതിന് നന്ദി!",
fail: "സമർപ്പിക്കൽ പരാജയപ്പെട്ടു",
error: "എന്തോ പിഴവ് സംഭവിച്ചു",
serverError: "സർവർ പിശക്",
serverErrorDesc: "റിപ്പോർട്ട് അയയ്ക്കാൻ കഴിഞ്ഞില്ല",
myDashboard: "എന്റെ ഡാഷ്ബോർഡ്",
coins: "നേടിയ നാണയങ്ങൾ",
submitted: "സമർപ്പിച്ച റിപ്പോർട്ടുകൾ",
completed: "പൂർത്തിയായ റിപ്പോർട്ടുകൾ",
rewards: "റിവാർഡുകൾ നേടുക",
redeem: "റീഡീം ചെയ്ത് സർട്ടിഫിക്കറ്റ് ഡൗൺലോഡ് ചെയ്യുക",
loginFirst: "ദയവായി ആദ്യം ലോഗിൻ ചെയ്യുക",
notEnoughCoins: "മതിയായ നാണയങ്ങൾ ഇല്ല",
redeemed: "റിവാർഡ് വിജയകരമായി ലഭിച്ചു",
recycleDesc: "മാലിന്യങ്ങൾ ശരിയായി കൈകാര്യം ചെയ്യുന്നത് പഠിച്ച് ശുചിയായ പരിസ്ഥിതിക്ക് സഹായിക്കൂ.",
solidWaste: "ഘന മാലിന്യം",
organicWaste: "സേന്ദ്രിയ മാലിന്യം",
hazardousWaste: "അപായകരമായ മാലിന്യം",

solidDesc: "പ്ലാസ്റ്റിക്, പേപ്പർ, ലോഹങ്ങൾ ഉൾപ്പെടുന്നു.",
organicDesc: "ഭക്ഷ്യ മാലിന്യം കമ്പോസ്റ്റ് ചെയ്യാം.",
hazardousDesc: "ബാറ്ററി, രാസവസ്തുക്കൾ പോലുള്ള അപകടകരമായ മാലിന്യം.",

tip1: "പ്ലാസ്റ്റിക് ഉപയോഗം കുറയ്ക്കുക",
tip2: "അടുക്കള മാലിന്യം കമ്പോസ്റ്റ് ചെയ്യുക",
tip3: "ഇ-വേസ്റ്റ് സുരക്ഷിതമായി റീസൈക്കിൾ ചെയ്യുക",

recycleQuote: "ശുചിയായ പരിസ്ഥിതി നമ്മുടെ ഭാവി സംരക്ഷിക്കുന്നു.",
aboutTitle: "ഞങ്ങളെക്കുറിച്ച്",
aboutDesc: "GO.CLEAN ഒരു സ്മാർട്ട് മാലിന്യ മാനേജ്മെന്റ് പ്ലാറ്റ്ഫോമാണ്.",

whatWeDo: "ഞങ്ങൾ എന്ത് ചെയ്യുന്നു",
whatDesc: "ഉപയോക്താക്കൾക്ക് ചിത്രം, സ്ഥലം എന്നിവയോടെ പ്രശ്നങ്ങൾ റിപ്പോർട്ട് ചെയ്യാം.",

howWeWork: "ഞങ്ങൾ എങ്ങനെ പ്രവർത്തിക്കുന്നു",
howDesc: "റിപ്പോർട്ടുകൾ അഡ്മിനിലേക്ക് പോകുന്നു.",

progressStatus: "സ്ഥിതി അപ്ഡേറ്റ്",
progressDesc: "Pending, In Progress അല്ലെങ്കിൽ Completed കാണുക.",

feature1: "ലൊക്കേഷൻ അടിസ്ഥാന റിപ്പോർട്ടിംഗ്",
feature2: "ഇമേജ് തെളിവ്",
feature3: "ലൈവ് ട്രാക്കിംഗ്",

aboutQuote: "ചെറിയ പ്രവർത്തനങ്ങൾ വലിയ മാറ്റം സൃഷ്ടിക്കുന്നു.",
home: "ഹോം",
report: "റിപ്പോർട്ട്",

treeCert: "മരം നട്ട് സർട്ടിഫിക്കറ്റ്",
cleanBadge: "ശുചിത്വ പൗര ബാഡ്ജ്",
smartAward: "സ്മാർട്ട് പൗര അവാർഡ്",
upcomingEvents: "വരുന്ന മുനിസിപ്പൽ ഇവന്റുകൾ",
eventsSubtitle: "മുനിസിപ്പൽ & കമ്മ്യൂണിറ്റി പ്രോഗ്രാമുകൾ",
loadingEvents: "ഇവന്റുകൾ ലോഡ് ചെയ്യുന്നു...", 
eventsError: "ഇവന്റുകൾ ലോഡ് ചെയ്യാൻ കഴിഞ്ഞില്ല",
tryAgainLater: "ദയവായി പിന്നീട് വീണ്ടും ശ്രമിക്കുക",
noEvents: "എന്തെങ്കിലും ഇവന്റുകൾ ലഭ്യമല്ല",
  },

  pa: {
    home: "ਹੋਮ",
    recycling: "ਰੀਸਾਈਕਲਿੰਗ",
    report: "ਰਿਪੋਰਟ",
    about: "ਬਾਰੇ",
    myReports: "ਮੇਰੀ ਰਿਪੋਰਟਾਂ",
    login: "ਲਾਗਇਨ",
    signup: "ਸਾਇਨ ਅੱਪ",
    logout: "ਲਾਗਆਉਟ",
    welcome: "ਸਵਾਗਤ",
    feed: "ਫੀਡ",

    heroTitle:
      "ਸਫਾਈ ਕੋਈ ਕਾਨੂੰਨ ਦੁਆਰਾ ਲਾਗੂ ਕੀਤੀ ਜ਼ਿੰਮੇਵਾਰੀ ਨਹੀਂ, ਸਗੋਂ ਸਮਾਜ ਪ੍ਰਤੀ ਸਾਡੀ ਜ਼ਿੰਮੇਵਾਰੀ ਹੈ।",
    heroSubtitle:
      "ਅੱਜ ਦੀ ਛੋਟੀ ਕੋਸ਼ਿਸ਼ ਕੱਲ੍ਹ ਨੂੰ ਸਾਫ ਬਣਾਉਂਦੀ ਹੈ।",
    recycleBtn: "ਰੀਸਾਈਕਲਿੰਗ ਆਈਡੀਆਜ਼",
    reportBtn: "ਰਿਪੋਰਟ",
    reportTitle: "ਕੂੜਾ ਸਮੱਸਿਆ ਰਿਪੋਰਟ ਕਰੋ",
binId: "ਡਸਟਬਿਨ ਆਈਡੀ",
issueType: "ਸਮੱਸਿਆ ਦੀ ਕਿਸਮ",
selectIssue: "ਸਮੱਸਿਆ ਚੁਣੋ",
selectIssueDesc: "ਕਿਰਪਾ ਕਰਕੇ ਸਮੱਸਿਆ ਦੀ ਕਿਸਮ ਚੁਣੋ",
illegal: "ਗੈਰਕਾਨੂੰਨੀ ਕੂੜਾ ਸੁੱਟਣਾ",
overflow: "ਭਰਿਆ ਹੋਇਆ ਡਸਟਬਿਨ",
damaged: "ਟੁੱਟਿਆ ਹੋਇਆ ਡਸਟਬਿਨ",
location: "GPS ਸਥਾਨ",
phone: "ਸੰਪਰਕ ਨੰਬਰ",
phonePlaceholder: "ਫੋਨ ਨੰਬਰ ਦਾਖਲ ਕਰੋ",
descPlaceholder: "ਸਮੱਸਿਆ ਦਾ ਵੇਰਵਾ ਦਿਓ...",
upload: "ਫੋਟੋ ਅੱਪਲੋਡ ਕਰੋ",
submit: "ਰਿਪੋਰਟ ਭੇਜੋ",
submitting: "ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ...",
success: "ਰਿਪੋਰਟ ਸਫਲਤਾਪੂਰਵਕ ਭੇਜੀ ਗਈ",
successDesc: "ਸ਼ਹਿਰ ਨੂੰ ਸਾਫ ਰੱਖਣ ਲਈ ਧੰਨਵਾਦ!",
fail: "ਸਬਮਿਸ਼ਨ ਅਸਫਲ",
error: "ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ",
serverError: "ਸਰਵਰ ਗਲਤੀ",
serverErrorDesc: "ਰਿਪੋਰਟ ਭੇਜਣ ਵਿੱਚ ਅਸਮਰੱਥ",
myDashboard: "ਮੇਰਾ ਡੈਸ਼ਬੋਰਡ",
coins: "ਕਮਾਏ ਗਏ ਕੋਇਨ",
submitted: "ਜਮ੍ਹਾਂ ਕੀਤੀਆਂ ਰਿਪੋਰਟਾਂ",
completed: "ਪੂਰੀਆਂ ਹੋਈਆਂ ਰਿਪੋਰਟਾਂ",
rewards: "ਇਨਾਮ ਪ੍ਰਾਪਤ ਕਰੋ",
redeem: "ਰੀਡੀਮ ਕਰੋ ਅਤੇ ਸਰਟੀਫਿਕੇਟ ਡਾਊਨਲੋਡ ਕਰੋ",
loginFirst: "ਕਿਰਪਾ ਕਰਕੇ ਪਹਿਲਾਂ ਲਾਗਇਨ ਕਰੋ",
notEnoughCoins: "ਪੂਰੇ ਕੋਇਨ ਨਹੀਂ ਹਨ",
redeemed: "ਇਨਾਮ ਸਫਲਤਾਪੂਰਵਕ ਪ੍ਰਾਪਤ ਕੀਤਾ ਗਿਆ",
recycleDesc: "ਕੂੜੇ ਦਾ ਸਹੀ ਪ੍ਰਬੰਧਨ ਸਿੱਖੋ ਅਤੇ ਸਾਫ਼ ਵਾਤਾਵਰਣ ਵਿੱਚ ਯੋਗਦਾਨ ਪਾਓ।",
solidWaste: "ਠੋਸ ਕੂੜਾ",
organicWaste: "ਜੈਵਿਕ ਕੂੜਾ",
hazardousWaste: "ਖਤਰਨਾਕ ਕੂੜਾ",

solidDesc: "ਪਲਾਸਟਿਕ, ਕਾਗਜ਼ ਅਤੇ ਧਾਤਾਂ ਸ਼ਾਮਲ ਹਨ।",
organicDesc: "ਖਾਣ-ਪੀਣ ਦਾ ਕੂੜਾ ਕੰਪੋਸਟ ਕੀਤਾ ਜਾ ਸਕਦਾ ਹੈ।",
hazardousDesc: "ਬੈਟਰੀਆਂ ਅਤੇ ਰਸਾਇਣ ਵਰਗਾ ਖਤਰਨਾਕ ਕੂੜਾ।",

tip1: "ਪਲਾਸਟਿਕ ਦੀ ਵਰਤੋਂ ਘਟਾਓ",
tip2: "ਰਸੋਈ ਦੇ ਕੂੜੇ ਨੂੰ ਕੰਪੋਸਟ ਕਰੋ",
tip3: "ਈ-ਵੇਸਟ ਨੂੰ ਸੁਰੱਖਿਅਤ ਤਰੀਕੇ ਨਾਲ ਰੀਸਾਈਕਲ ਕਰੋ",

recycleQuote: "ਸਾਫ਼ ਵਾਤਾਵਰਣ ਸਾਡਾ ਭਵਿੱਖ ਬਚਾਉਂਦਾ ਹੈ।",
aboutTitle: "ਸਾਡੇ ਬਾਰੇ",
aboutDesc: "GO.CLEAN ਇੱਕ ਸਮਾਰਟ ਕੂੜਾ ਪ੍ਰਬੰਧਨ ਪਲੇਟਫਾਰਮ ਹੈ।",

whatWeDo: "ਅਸੀਂ ਕੀ ਕਰਦੇ ਹਾਂ",
whatDesc: "ਯੂਜ਼ਰ ਫੋਟੋ ਅਤੇ ਲੋਕੇਸ਼ਨ ਨਾਲ ਸਮੱਸਿਆ ਰਿਪੋਰਟ ਕਰ ਸਕਦੇ ਹਨ।",

howWeWork: "ਅਸੀਂ ਕਿਵੇਂ ਕੰਮ ਕਰਦੇ ਹਾਂ",
howDesc: "ਰਿਪੋਰਟ ਐਡਮਿਨ ਨੂੰ ਭੇਜੀ ਜਾਂਦੀ ਹੈ ਅਤੇ ਹੱਲ ਕੀਤੀ ਜਾਂਦੀ ਹੈ।",

progressStatus: "ਸਥਿਤੀ ਅਪਡੇਟ",
progressDesc: "Pending, In Progress ਜਾਂ Completed ਵੇਖੋ।",

feature1: "ਲੋਕੇਸ਼ਨ ਅਧਾਰਿਤ ਰਿਪੋਰਟਿੰਗ",
feature2: "ਇਮੇਜ ਸਬੂਤ",
feature3: "ਲਾਈਵ ਟ੍ਰੈਕਿੰਗ",

aboutQuote: "ਛੋਟੀਆਂ ਕਾਰਵਾਈਆਂ ਵੱਡਾ ਬਦਲਾਅ ਲਿਆਉਂਦੀਆਂ ਹਨ।",
home: "ਹੋਮ",
report: "ਰਿਪੋਰਟ",

treeCert: "ਰੁੱਖ ਲਗਾਉਣ ਸਰਟੀਫਿਕੇਟ",
cleanBadge: "ਸਾਫ਼ ਸੁਥਰਾ ਨਾਗਰਿਕ ਬੈਜ",
smartAward: "ਸਮਾਰਟ ਨਾਗਰਿਕ ਇਨਾਮ",
upcomingEvents: "ਆਉਣ ਵਾਲੇ ਮਿਊਨਿਸਿਪਲ ਇਵੈਂਟਸ",
eventsSubtitle: "ਮਿਊਨਿਸਿਪਲ ਅਤੇ ਕਮਿਊਨਿਟੀ ਪ੍ਰੋਗਰਾਮ",
loadingEvents: "ਇਵੈਂਟਸ ਲੋਡ ਹੋ ਰਹੇ ਹਨ...",
eventsError: "ਇਵੈਂਟਸ ਲੋਡ ਨਹੀਂ ਕਰ ਸਕੇ",
tryAgainLater: "ਕਿਰਪਾ ਕਰਕੇ ਬਾਅਦ ਵਿੱਚ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ करें",
noEvents: "ਕੋਈ ਇਵੈਂਟ्स उपलब्ध नहीं हैं",
  }
};



export default langData;